#!/usr/bin/env bash

HYPRGAMEMODE=$(hyprctl getoption animations:enabled | sed -n '1p' | awk '{print $2}')
NOTIFICATION_TIME_MS=1000

# Waybar performance
FILE="$HOME/.config/waybar/style.css"

sed -i 's/\/\* \(.*animation:.*\) \*\//\1/g' "$FILE"
sed -i 's/\/\* \(.*transition:.*\) \*\//\1/g' "$FILE"

# Modify Waybar style if in gaming mode
if [ "$HYPRGAMEMODE" = 1 ]; then
    sed -i 's/^\(.*animation:.*\)$/\/\* \1 \*\//g' "$FILE"
    sed -i 's/^\(.*transition:.*\)$/\/\* \1 \*\//g' "$FILE"
fi

# Function to start or stop swww-daemon based on gaming mode
manage_swww_daemon() {
    echo $HYPRGAMEMODE
    if [ "$HYPRGAMEMODE" = 1 ]; then
        hyprctl notify 5 $NOTIFICATION_TIME_MS 0 "GAMEMODE ON"
        pkill -u $USER mpvpaper
        pkill -u $USER swww-daemon
    else
        hyprctl notify 4 $NOTIFICATION_TIME_MS 0 "GAMEMODE OFF"
        swww-daemon &>/dev/null & # Start swww-daemon if not in gaming mode
    fi
}

manage_swww_daemon

# Hyprland performance adjustments
if [ "$HYPRGAMEMODE" = 1 ]; then
    hyprctl --batch "\
        keyword animations:enabled 0;\
        keyword decoration:shadow:enabled 0;\
        keyword decoration:blur:enabled 0;\
        keyword general:gaps_in 0;\
        keyword general:gaps_out 0;\
        keyword general:border_size 1;\
        keyword decoration:rounding 0"
    exit
else
    hyprctl reload
fi
