#!/usr/bin/env bash

NOTES_DIR="$HOME/.notes"

open_notes() {
    if [ -z "$TERMINAL" ]; then
        echo "TERMINAL variable is not set." >&2
        exit 1
    fi

    # Sourcing ~/.zshrc otherwise pywal colorscheme won't apply.
    # NOTE: This will probably only work with the zshell.
    $TERMINAL -e $SHELL -c "source ~/.zshrc && cd $NOTES_DIR && exec nvim note.txt"
}

# Ensure the notes directory exists
mkdir -p "$NOTES_DIR"

open_notes
